import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://localhost:3000';
const catalog=await fetch(`${base}/api/catalog`).then(r=>r.json());
assert.equal(catalog.products.length,74);
assert.equal(catalog.settings.ordersEnabled,false,'Execute os testes em demonstração.');
for(const path of ['/','/sabores','/cardapio','/nossa-essencia','/visite','/checkout','/pagamento','/pedidos','/privacidade','/admin'])assert.equal((await fetch(base+path)).status,200,path);
const input={requestKey:crypto.randomUUID(),items:[{id:'margherita',halfId:'calabresa-coberta',size:'grande',quantity:1,note:''}],customer:{name:'Teste Donna',phone:'15999999999',email:'teste@example.com'},fulfillment:'delivery',address:{street:'Rua de Teste',number:'1',neighborhood:'Centro',complement:'',city:'Sorocaba',zip:'18090-070'},coupon:'',consent:true,demo:true};
const post=(data,origin=base)=>fetch(`${base}/api/orders`,{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(data)});
let res=await post(input);assert.equal(res.status,201);let order=await res.json();assert.equal(order.order.total,8300,'Meio a meio é média (75) + entrega (8).');assert.equal(order.order.data.customer,undefined,'Demonstração local não persiste dados de contato.');
res=await post({...input,fulfillment:'pickup'});assert.equal((await res.json()).order.total,7500,'Retirada sem taxa.');
res=await post({...input,items:[{...input.items[0],halfId:undefined,size:'individual'}],fulfillment:'pickup'});assert.equal((await res.json()).order.total,catalog.products.find(p=>p.id==='margherita').individualPrice);
res=await post({...input,items:[{...input.items[0],halfId:'brigadeiro'}]});assert.equal(res.status,400,'Salgada e doce não devem se misturar.');
res=await post({...input,items:[{...input.items[0],quantity:21}]});assert.equal(res.status,400);
res=await post({...input,items:[{...input.items[0],id:'nao-existe'}]});assert.equal(res.status,400);
res=await post({...input,coupon:'INVALIDO'});assert.equal(res.status,400);
res=await post({...input,customer:{...input.customer,phone:'123'}});assert.equal(res.status,400);
res=await post({...input,address:{...input.address,zip:'00000-000'}});assert.equal(res.status,400);
res=await post({...input,demo:false});assert.equal(res.status,409,'Não ativar modo real pelo cliente.');
res=await post(input,'https://example.invalid');assert.equal(res.status,403);
res=await fetch(`${base}/api/admin`,{headers:{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'admin@example.com'}});assert.equal((await res.json()).authorized,false);
res=await fetch(`${base}/api/payment/webhook`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:{id:'1'},status:'approved'})});assert.ok([401,503].includes(res.status),'Webhook sem assinatura não aprova pagamento.');
console.log('PASS: 10 páginas, 74 sabores, média, broto, retirada, validações, origem e controles de acesso.');
