import {z} from 'zod';
import {catalog,db,json,failure,sameOrigin,body,owner,ipHash,ApiError,runtime,mp,databaseConfigured,paymentsReady} from '@/lib/server';
import {unitPrice} from '@/lib/catalog';
const schema=z.object({requestKey:z.string().uuid(),items:z.array(z.object({id:z.string().min(1).max(80),halfId:z.string().max(80).optional(),size:z.enum(['individual','grande']),quantity:z.number().int().min(1).max(20),note:z.string().max(200)})).min(1).max(20),customer:z.object({name:z.string().trim().min(2).max(100),phone:z.string().regex(/^\(?\d{2}\)?\s?\d{4,5}[-\s]?\d{4}$/),email:z.string().email().max(180)}),fulfillment:z.enum(['delivery','pickup']),address:z.object({street:z.string().max(140),number:z.string().max(20),neighborhood:z.string().max(100),complement:z.string().max(100),city:z.string().max(80),zip:z.string().max(10)}),coupon:z.string().max(40),consent:z.literal(true),demo:z.boolean()});
export async function GET(request:Request){try{const who=await owner(request);if(!databaseConfigured())return json({orders:[],storage:'browser'},200,who.cookie?{'Set-Cookie':who.cookie}:{});const rows=await db().prepare('SELECT id, data, total, demo, status, payment, created FROM orders WHERE owner = ? ORDER BY created DESC LIMIT 50').bind(who.id).all();return json({orders:rows.results.map((r:any)=>({...r,data:JSON.parse(r.data)}))},200,who.cookie?{'Set-Cookie':who.cookie}:{});}catch(e){return failure(e);}}
export async function POST(request:Request){try{sameOrigin(request);const parsed=schema.safeParse(await body(request));if(!parsed.success)throw new ApiError('Confira nome, telefone com DDD, e-mail e os dados do pedido.');const input=parsed.data;const who=await owner(request);const headers:Record<string,string>=who.cookie?{'Set-Cookie':who.cookie}:{};const prior:any=databaseConfigured()?await db().prepare('SELECT id, owner, data, demo FROM orders WHERE request_key = ?').bind(input.requestKey).first():null;if(prior){if(prior.owner!==who.id)throw new ApiError('Identificador já utilizado.',409);const data=JSON.parse(prior.data);if(!prior.demo&&!data.checkoutUrl)throw new ApiError('O pagamento ainda está sendo preparado. Consulte seus pedidos antes de tentar novamente.',409);return json({id:prior.id,demo:!!prior.demo,checkoutUrl:data.checkoutUrl},200,headers);}
const ip=await ipHash(request);const recent:any=databaseConfigured()?await db().prepare('SELECT COUNT(*) AS count FROM orders WHERE ip_hash = ? AND created > ?').bind(ip,Date.now()-3600000).first():{count:0};if(recent.count>=15)throw new ApiError('Limite temporário de pedidos atingido. Aguarde um pouco.',429);
const {products,settings}=await catalog();const demo=!settings.ordersEnabled;if(input.demo!==demo)throw new ApiError('O modo da loja mudou. Recarregue o checkout.',409);if(!settings.open)throw new ApiError('A loja está com os pedidos pausados.');if(!demo&&!paymentsReady())throw new ApiError('O pagamento online ainda não está disponível.',503);
if(input.items.reduce((sum,i)=>sum+i.quantity,0)>20)throw new ApiError('Para mais de 20 itens, fale com a pizzaria.');
const lines=input.items.map(i=>{const p=products.find(p=>p.id===i.id);const half=products.find(p=>p.id===i.halfId);if(!p||!p.available)throw new ApiError('Um item ficou indisponível. Atualize sua sacola.');if(i.halfId&&(!half||!half.available||i.size!=='grande'||p.category==='Bebidas'||half.category==='Bebidas'||(p.category==='Doces')!==(half.category==='Doces')))throw new ApiError('Combinação de sabores inválida.');if(i.size==='individual'&&p.category!=='Bebidas'&&!p.individualPrice)throw new ApiError('Tamanho broto indisponível para este sabor.');return {...i,name:p.name+(half?` / ${half.name}`:''),price:unitPrice(i,products)};});
if(input.fulfillment==='delivery'&&(!input.address.street.trim()||!input.address.number.trim()||!input.address.neighborhood.trim()||input.address.city.trim().toLowerCase()!=='sorocaba'||!/^180\d{2}-?\d{3}$/.test(input.address.zip)))throw new ApiError('Informe um endereço completo de Sorocaba e um CEP válido.');
const subtotal=lines.reduce((s,i)=>s+i.price*i.quantity,0);if(input.coupon&&input.coupon.trim().toUpperCase()!==settings.coupon.toUpperCase())throw new ApiError('Cupom inválido.');const discount=input.coupon&&settings.coupon?Math.round(subtotal*settings.discount/100):0;const delivery=input.fulfillment==='delivery'?settings.deliveryFee:0;const total=subtotal-discount+delivery;const id=crypto.randomUUID();const data={customer:input.customer,address:input.fulfillment==='delivery'?input.address:null,fulfillment:input.fulfillment,lines,subtotal,discount,delivery,coupon:input.coupon,consentAt:new Date().toISOString(),checkoutUrl:null as string|null};
if(!databaseConfigured())return json({id:input.requestKey,demo:true,storage:'browser',order:{id:input.requestKey,total,demo:1,status:'demo',payment:'demo',created:Date.now(),data:{lines,fulfillment:input.fulfillment,subtotal,discount,delivery}}},201,headers);
await db().prepare('INSERT INTO orders (id, owner, request_key, ip_hash, data, total, demo, status, payment, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(id,who.id,input.requestKey,ip,JSON.stringify(data),total,demo?1:0,demo?'demo':'aguardando_pagamento',demo?'demo':'pending',Date.now()).run();
if(!demo){try{const origin=new URL(runtime().SITE_URL!).origin;const preference=await mp('/checkout/preferences','POST',{items:[{id,title:'Pedido Donna Florinda',quantity:1,currency_id:'BRL',unit_price:total/100}],payer:{email:input.customer.email},external_reference:id,back_urls:{success:`${origin}/pagamento?pedido=${id}`,failure:`${origin}/pagamento?pedido=${id}`,pending:`${origin}/pagamento?pedido=${id}`},notification_url:`${origin}/api/payment/webhook`,auto_return:'approved'},id);if(!preference.init_point)throw Error('Checkout ausente');const url=new URL(preference.init_point);if(url.protocol!=='https:'||!/(^|\.)mercadopago\.(com|com\.br)$/.test(url.hostname))throw Error('Checkout inválido');data.checkoutUrl=url.href;await db().prepare('UPDATE orders SET data = ? WHERE id = ?').bind(JSON.stringify(data),id).run();}catch(e){await db().prepare("UPDATE orders SET status = 'falha_pagamento' WHERE id = ?").bind(id).run();throw e;}}
return json({id,demo,checkoutUrl:data.checkoutUrl},201,headers);
}catch(e){return failure(e);}}
